### ISSUE TITLE
Infra NuGets

### ISSUE THREAD

**Issue by bnaya-corp** [bnaya-corp/todo#3]
- [NLN - Infra Team Upgrade Status](https://dev.azure.com/Payoneer/Payoneer/_wiki/wikis/Payoneer.wiki/9406/NLN-Infra-Team-Upgrade-Status)
-  [Old Open API](https://dev.azure.com/Payoneer/Payoneer/_wiki/wikis/Payoneer.wiki/17000/Adding-methods-in-OpenAPI-(V4)-Guidelines?anchor=applying-openapi-format-for-json-serialization-)
- [Multi Frameworks](https://learn.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file)

- [ ] ~~NewtonsoftJson~~ should die 
- [ ] AddPayoneerStandard & UsePayoneerStandard extension method: should encapsulate must have settings and injections
  - [ ] Open Telemetry
- [ ]  Suggestion & Enforcement should govern by Static Code Analyzer
- [ ] Use grouping NuGet to bundle different infra NuGets together 
- [ ] [Error Handling](https://dev.azure.com/Payoneer/Payoneer/_git/accountsecurity-infrastructure-exception-handling?path=/src/ExceptionHandling/ExceptionHandling.csproj)
  - [ ] [Error Handling registration](https://dev.azure.com/Payoneer/Payoneer/_git/infrastructure-template-front-end?path=/WebApi/Program.cs&version=GBmaster&line=54&lineEnd=56&lineStartColumn=1&lineEndColumn=76&lineStyle=plain&_a=contents)

**Comment by bnaya-corp** [comment]
- 30-40 different places use it, and growing

> - Security Responsibility
>    - JWT
>    - Claims
>    - Authorization

OPEN API:


- Serialization
![Image](https://github.com/bnaya-payoneer/todo/assets/144127531/3745be69-f9a4-4734-9e31-637e9c4e664d)

  - [Using Multi serialization setting in a project](https://thomaslevesque.com/2022/09/19/using-multiple-json-serialization-settings-in-aspnet-core/)
  
- Route
![Image](https://github.com/bnaya-payoneer/todo/assets/144127531/d3a43153-43fd-431d-928c-1fade436eac8)


- Exception
![Image](https://github.com/bnaya-payoneer/todo/assets/144127531/8c4af54f-6dc7-4ec3-b3cd-cc1051a870ee)
Error standard 
  - TBD: take the format from the chat
  - [Exception Handling](https://learn.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file)

- Response

<img src="https://github.com/bnaya-payoneer/todo/assets/144127531/61bda632-9166-4584-b406-e7c555446269" width=400px/>

- Middleware

![Image](https://github.com/bnaya-payoneer/todo/assets/144127531/30ee1896-5a7d-4ccc-a823-7642bab146ce)


![Image](https://github.com/bnaya-payoneer/todo/assets/144127531/50f676fb-6628-4217-a0b9-cdf574fb5930)

**Comment by bnaya-corp** [comment]
```cs
public class ErrorResponse
    {
        [JsonProperty("error")]
        public string Error { get; set; }
        [JsonProperty("error_description")]
        public string ErrorDescription { get; set; }
 
        [JsonProperty("error_details")]
        public ErrorDetails ErrorDetails { get; set; }
    }
```
```cs
public class ErrorDetails
    {
        [JsonProperty("code")]
        public int Code { get; set; }
 
        [JsonProperty("sub_code")]
        public int SubCode { get; set; }
 
        public bool ShouldSerializeSubCode()
        {
            return SubCode != 0;
        }
    }
```

**Comment by bnaya-corp** [comment]
Multi version should be deprecated
[repo](https://dev.azure.com/Payoneer/Payoneer/_git/platformsecurity-infrastructure-security-middleware?path=%2Fsrc%2FSecurityMiddleware%2FSwagger%2FOnlyAppliesToAttribute.cs&_a=contents&version=GBmaster)

```cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace Payoneer.SecurityInfrastructure.SecurityMiddleware.Swagger
{
    [AttributeUsage(AttributeTargets.Method | AttributeTargets.Class)]
    public sealed class OnlyAppliesToAttribute : Attribute
    {
        private IEnumerable<string> _versions;

        public OnlyAppliesToAttribute(params object[] versions)
        {
            _versions = versions.Select(o => o.ToString());
        }
        public IEnumerable<string> GetVersions()
        {
            return _versions;
        }
    }
}
```

**Comment by bnaya-corp** [comment]
RISK: 
- Services declared on a multi version support
  - The OnlyAppliesTo should limit to support a single version
- OnlyAppliesTo sets on methods
  - should limit to classes  
- TODO: speak with @Jenya Tsybulevsky

**Comment by bnaya-corp** [comment]
# TODO: check it

[Search](https://dev.azure.com/Payoneer/Payoneer/_search?action=contents&text=Payoneer.ServicesInfra.WebApi.ExceptionHandling&type=code&lp=code-Project&filters=ProjectFilters%7BPayoneer%7DRepositoryFilters%7Binfrastructure-infrastructure-webapi*infrastructure-webapi-infrastructure%7D&pageSize=25&result=DefaultCollection/Payoneer/infrastructure-infrastructure-webapi/GBmaster//Payoneer.ServicesInfra.WebApi.ExceptionHandling/Payoneer.ServicesInfra.WebApi.ExceptionHandling.csproj)

[infrastructure-infrastructure-webapi](https://dev.azure.com/Payoneer/Payoneer/_git/infrastructure-infrastructure-webapi?path=%2FPayoneer.ServicesInfra.WebApi.ExceptionHandling%2FPayoneer.ServicesInfra.WebApi.ExceptionHandling.csproj&_a=contents&version=GBmaster)
.NET 4.6.1
Payoneer.ServicesInfra.WebApi.ExceptionHandling	 	 	 	 
Payoneer.ServicesInfra.WebApi.ClientIdentification	 	 	 	 	 
Payoneer.ServicesInfra.WebApi.Models	 	 	 	 	 
Payoneer.ServicesInfra.WebApi.SystemIdentification	 	 	 	 	 
 

Payoneer.Infrastructure.Net
Payoneer.Infrastructure.NetCore.Extensions.Swagger ? (check usage in template)
 
[infrastructure-webapi-infrastructure](https://dev.azure.com/Payoneer/Payoneer/_git/infrastructure-webapi-infrastructure)
.NET 4.6.1, .NET Core 3.1, .NET Standard 2.0, 
Payoneer.ServicesInfra.Controllers	 	 	 	 	 
Payoneer.ServicesInfra.Controllers.NetCore	 	 	 	 	 
Payoneer.ServicesInfra.WebAPI.Validation	 	 	 	 	 
Payoneer.ServicesInfra.InitializeDefinitions

**Comment by bnaya-corp** [comment]
[infrastructure-infrastructure-webapi](https://dev.azure.com/Payoneer/Payoneer/_git/infrastructure-infrastructure-webapi?path=%2FPayoneer.ServicesInfra.WebApi.ExceptionHandling%2FPayoneer.ServicesInfra.WebApi.ExceptionHandling.csproj&_a=contents&version=GBmaster)


![Image](https://github.com/bnaya-payoneer/todo/assets/144127531/3b08a66b-6971-40f5-8596-2b70a9702703)

**Comment by bnaya-corp** [comment]
# Modern Health Check 

- [The Best Way to Add Health Checks in Any .NET App](https://www.youtube.com/watch?v=p2faw9DCSsY)
- [Health Check Docs](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-8.0)
- [Article](https://medium.com/microservicesuniversity/health-check-in-net-6-0-4516f5205223)

**Comment by bnaya-corp** [comment]
Swager sample:
https://github.dev/Amitpnk/Onion-architecture-ASP.NET-Core/blob/e4c1d43ec4923db0784a2264f8fac2e86053a51c/src/OA.Infrastructure/Extension/ConfigureServiceContainer.cs#L127#L138

**Comment by bnaya-corp** [comment]
[3:19 PM] Arnold Simha
https://youtu.be/E_bkN_KperE?si=U2yju6eZf8ldNHOy
 like 2
.NET Developers should be using dotnet-outdated to update their project's references - YouTube
.NET Developers should be using dotnet-outdated to update their project's references https://github.com/dotnet-outdated/dotnet-outdated
