### ISSUE TITLE
Infra Template

### ISSUE THREAD

**Issue by bnaya-corp** [bnaya-corp/todo#5]
[PBI](https://dev.azure.com/Payoneer/Payoneer/_workitems/edit/845553)

[Template Repo](https://dev.azure.com/Payoneer/Payoneer/_git/infrastructure-template-net8-api-service)

- System.Text.Json
  - [Feature comparison](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft?pivots=dotnet-8-0)
- OTEL
  - [Corallogix](https://coralogix.zoom.us/rec/play/yocsgte5PfVGpLdlQW9rTsrc2-1rmA0gMfmZrYHkzX4aUKhBU_w6uysjL0A6924_xTwehkpozztQfyV5.8V6Izt_09X84GgHt?canPlayFromShare=true&from=share_recording_detail&startTime=1698922749000&componentName=rec-play&originRequestUrl=https%3A%2F%2Fcoralogix.zoom.us%2Frec%2Fshare%2FXIb6LO7_08NNDeywXBlCE9jf_PYZOnMLKdTsn_Y2cfTxLn1uTXwXdppJctPG8tys.eT_wBI-MuTHG8tzu%3FstartTime%3D1698922749000): FileBit is Old, recommend to move into OTEL [3:08, Passcode: `fGOd7+&.`]

- Swagger version
- Common Docker Compose (base-line, mongo, sql-server, etc.)
- [Mongo WiKi](https://dev.azure.com/Payoneer/Payoneer/_wiki/wikis/Payoneer.wiki/11469/MongoDB-Release-Management-CI-CD)

Each switch should have a WIKI page which will be address from the ReadMe.md

**Comment by bnaya-corp** [comment]
- Pubcom: Remove, Check Easychaching
- NLog: Remove
- Add HealthCheck.
- v1, v2 convention [Obsolete]

**Comment by bnaya-corp** [comment]
Check Api Versioning:
- Bnaya Demo: https://github.com/bnaya-payoneer/ApiVersioningDemo
- https://code-maze.com/aspnetcore-api-versioning/
- https://www.milanjovanovic.tech/blog/api-versioning-in-aspnetcore
- https://weblogs.asp.net/ricardoperes/asp-net-core-api-versioning

**Comment by bnaya-corp** [comment]
# Guidelines

- [ ] The template will be modular via switches
  - [ ] Each switch should have a WIKI page which will be address from the ReadMe.md
  - [ ] legacy switch will provide the legacy template as it's before this initiative 
  - [ ] have switches to append modules to existing repo (created by this template)
- [ ] If possible, the template will trigger DevOps Portal via API to generate a repo and activate the pipeline
- [ ] Prefer `record` over `class` for data object


# Wish List

- [x] Healthcheck
- [x] Http Client
- [ ] GZip
- [ ] Redis Pub/Sub
- [ ] ILogger
  - [ ] Remove NLog dependencies
  - [ ] Sample for right Logging generator pattern
- [ ] [Caching](https://medium.com/@cizu64/distributed-caching-with-redis-and-response-caching-in-asp-net-core-8-169d7c6a7d3b):
  - [ ] Redis Distributed Cache
  - [ ] Remove [Pub-comp](https://github.com/pub-comp/caching): Remove (PostSharp!)
  - [ ]  Check [Easychaching](https://github.com/dotnetcore/EasyCaching) @Arnold
  - [ ] Use [Response Caching](Response caching)
- [ ] EF Coupling 
- [ ] Dapper
- [ ] GraphQL:
  - [Data Loader](https://medium.com/@vickytr44/hot-chocolate-grapghql-data-loaders-for-graphql-in-net-core-6-b2134cf3dfa8)
    - [Video](https://www.youtube.com/watch?v=an0Dlltfl1I) 
  -  [Article](https://www.learmoreseekmore.com/2021/10/a-demo-on-hot-chocolate-graphql-integration-in-aspnetcore-application-using-dapper-micro-orm.html)
  - [Video](https://www.youtube.com/watch?v=9MjTMMvuJR4)
- [ ] Mongo
  - [ ] Events 
- [ ] Open Telemetry
  - [ ] Kafka  
- [ ] Versioning convention v1, v2 
  - [ ] use [Obsolete] for retirement
- [ ] Setup a Wiki
- [ ] [AsyncApi](https://swagger.io/blog/using-event-driven-asyncapi-specifications-with-sw/) (Swagger for event-based pattern) [Payoneer](http://initiatorservice.qa.payoneer.com/asyncapi/ui/index.html)
- [ ] Mono-repo
- [ ] remove: wwwroot
- [ ] Docker
  - [ ] Dockerfile
  - [ ] Docker Compose
  - [ ] Tests with Docker Compose
  - [ ] [WebApplicationFactory](https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-8.0)
    - [Video](https://www.youtube.com/watch?v=zaRM0iIhJvs) 
- [ ] Testing
  - [ ] Remove [PostSharp](https://teams.microsoft.com/l/message/19:be926af4-afde-46f1-b56f-c68ce662ede3_e61601ec-746e-452b-80f4-c47b29e9c9b9@unq.gbl.spaces/1709121777553?context=%7B%22contextType%22%3A%22chat%22%7D) 
- [ ] Data Event 
  - [ ] Via Debezium [DeOutbox Event Routerbisium](https://debezium.io/documentation/reference/stable/transformations/outbox-event-router.html) an [Kafka Connect](https://docs.confluent.io/platform/current/connect/index.html)
  - [ ] TBD: [EventualizeDb](https://github.com/outsidenote/eventualize) and [Kafka Connect](https://docs.confluent.io/platform/current/connect/index.html)

Notes:
- Minimal Api + Controllers
- Remove `.ConfigureAwait(false)`
- `return Ok(result.ToContractEnumerable())`?
- Prefer immutability 
  - Services should return ImmutableArray or Array rather than `public async Task<IEnumerable<ExampleModel>> GetAsync()`
-  Should the sample be based on EF? `ExampleDomainContext context

**Comment by bnaya-corp** [comment]
# Infra.V2
https://dev.azure.com/Payoneer/Payoneer/_git/infrastructure-healthcheck-netcore-extensions?path=/WebApplication2/Program.cs&version=GBbnaya/dotnet-8&_a=contents

# Health: 

- [The Best Way to Add Health Checks in Any .NET App](https://www.youtube.com/watch?v=p2faw9DCSsY)
- [Health Check Docs](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-8.0)
- [Article](https://medium.com/microservicesuniversity/health-check-in-net-6-0-4516f5205223)

## Current State
https://dev.azure.com/Payoneer/Payoneer/_git/datacollection-profile-service?path=/ProfileService.WebApi/Startup.cs

Payoneer.Infrastructure.HealthCheckNetcoreExtensions

**Comment by bnaya-corp** [comment]
# domain-repo

- [Sample](https://dev.azure.com/Payoneer/Payoneer/_git/account-internal-payments?version=GBchanges%2Fssdts)
- [Card](https://dev.azure.com/Payoneer/Payoneer/_git/test-cards?version=GBchanges%2Fstructure)

# mono-repo

[gbt-psfx-glps-engine](https://dev.azure.com/Payoneer/Payoneer/_git/gbt-psfx-glps-engine)
[gbt-providers-integration](https://dev.azure.com/Payoneer/Payoneer/_git/gbt-providers-integration)
[paycloud-compliance-kycv - Repos (azure.com)](https://dev.azure.com/Payoneer/Payoneer/_git/paycloud-compliance-kycv)

## TODO

- [ ] Agree on the structure (architects)
  - [ ] Trunk based  
- [ ] Cli call DevOps portal
- [ ] Setup a structure
  - [ ] @Shay Lami: close the ci/cd flow
    - [ ] Deploy only changes
    - [ ] Directory.Build.props (no version)
    - [ ] Wishful: reference enforcement
- [ ] Standard
  - [ ]  TBD: Error details: https://www.rfc-editor.org/rfc/rfc7807.html @Jonathan Horowitz (not compatible with our Open API)

## Features

- [ ] Sub-Repo: Verticals
- [ ] Shared: cross domain's contracts, domain's infa
- [ ] Pipelines: Common + for each Sub Repo
- [ ] Sonar Cube: coverage false alarm
- [ ] Reference enforcement
- [ ] Directory.Build.props (no version)
- [ ] Testing & Automation: 
  - [ ] XUnit (@Tal Ainvoner) 
- [ ] Wishful: reference enforcement


Review @Ram Yaari

**Comment by bnaya-corp** [comment]
# [Polly](https://github.com/App-vNext/Polly)

```cs
var services = new ServiceCollection();

// Define a resilience pipeline with the name "my-pipeline"
services.AddResiliencePipeline("my-pipeline", builder =>
{
    builder
        .AddRetry(new RetryStrategyOptions())
        .AddTimeout(TimeSpan.FromSeconds(10));
});

// Build the service provider
var serviceProvider = services.BuildServiceProvider();

// Retrieve a ResiliencePipelineProvider that dynamically creates and caches the resilience pipelines
var pipelineProvider = serviceProvider.GetRequiredService<ResiliencePipelineProvider<string>>();

// Retrieve your resilience pipeline using the name it was registered with
ResiliencePipeline pipeline = pipelineProvider.GetPipeline("my-pipeline");

// Alternatively, you can use keyed services to retrieve the resilience pipeline
pipeline = serviceProvider.GetRequiredKeyedService<ResiliencePipeline>("my-pipeline");

// Execute the pipeline
await pipeline.ExecuteAsync(static async token =>
{
    // Your custom logic goes here
});
```

```cs
 _pipeline = new ResiliencePipelineBuilder()
    .AddRetry(new RetryStrategyOptions()) // Add retry using the default options
    .AddTimeout(TimeSpan.FromSeconds(10)) // Add 10 seconds timeout
    .Build(); // Builds the resilience pipeline
```



![Image](https://github.com/bnaya-payoneer/todo/assets/144127531/0100a5da-de6a-4e51-9c85-d7271fd9812b)

**Comment by bnaya-corp** [comment]
# OTEL 

## Logging

- UseW3CLogging: [here](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/w3c-logger/?view=aspnetcore-6.0) and [here](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.httploggingbuilderextensions.usew3clogging?view=aspnetcore-8.0)

**Comment by bnaya-corp** [comment]
# Outbox Pattern

- [WIKI](https://dev.azure.com/Payoneer/Payoneer/_wiki/wikis/Payoneer.wiki/11602/The-outbox-pattern)
- [debezium](https://github.com/debezium/debezium-examples/tree/main)
  - [Sample](https://github.com/debezium/debezium-examples/blob/main/outbox/README.md)
  - [Confluence Kafka Avro](https://debezium.io/documentation/reference/stable/configuration/avro.html)

**Comment by bnaya-corp** [comment]
# Devops Portal


![Image](https://github.com/bnaya-payoneer/todo/assets/144127531/da93438c-3ab2-42be-902d-dea0f0ffea11)



![Image](https://github.com/bnaya-payoneer/todo/assets/144127531/47892df7-d7c9-43e8-9108-9724979cd3df)

**Comment by bnaya-corp** [comment]
# Logging

## TODO

- [ ] Speak with Coralogix about the right way to propagate logs + OTEL span / correlation
- [ ] Speak with @Yuval Glasman - SRE 
  - [ ] Discussion about how to replace the nlog.config files in order to have json-formatted logs in Coralogix
    [Sample](https://dev.azure.com/Payoneer/Payoneer/_git/infrastructure-tours-service/commit/9cd795824943b0a0df7191feeb6650fbd0ab5c89?refName=refs/heads/feature/823838-change-logging-format&path=/WebApi/nlog.config)
  - [ ] Dynamic changes of filtering

**Comment by bnaya-corp** [comment]
# EF

- [Common mistakes in EF Core](https://www.youtube.com/watch?v=dDANjr5MCew)
- [Sample with Compiled Query](https://www.youtube.com/watch?v=OxqAUIYemMs&list=WL&index=3)

**Comment by bnaya-corp** [comment]
# Distributed Lock

- [RedLock](https://github.com/samcook/RedLock.net)

**Comment by bnaya-corp** [comment]
Error Details:
Consider using : https://www.rfc-editor.org/rfc/rfc7807.html

**Comment by bnaya-corp** [comment]
# Docker

## Integration Tests

- [Test Containers](https://dotnet.testcontainers.org/)
  - [Modules](https://dotnet.testcontainers.org/modules/)
  - [Sample test within a container](https://dotnet.testcontainers.org/examples/aspnet/)
  - [GitHub](https://github.com/testcontainers/testcontainers-dotnet)

**Comment by bnaya-corp** [comment]
# WireMock Server

```xml
<PackageReference Include="WireMock.Net" Version="1.5.56" />
```

```cs
using System.Net;
using WireMock.RequestBuilders;
using WireMock.ResponseBuilders;
using WireMock.Server;

namespace Payoneer.RV_Domain_RV.RV_AppName_RV.WebApi.Tests.Integration;

public class GitHubApiServer : IDisposable
{
    private WireMockServer _server;
    public string Url => _server.Url!;

    public GitHubApiServer()
    {
        _server = WireMockServer.Start();
    }


    public void SetupOkUser(string username)
    {
        _server.Given(Request.Create()
            .WithPath($"/users/{username}")
            .UsingGet())
            .RespondWith(Response.Create()
                .WithBody(GenerateOkGitHubUserResponseBody(username))
                .WithHeader("content-type", "application/json; charset=utf-8")
                .WithStatusCode(HttpStatusCode.OK));
    }
    private static string GenerateOkGitHubUserResponseBody(string username)
    {
        return $@"{{
            ""login"": ""{username}"",
            ""id"": {Math.Abs(username.GetHashCode())},
            ""url"": ""https://api.github.com/users/{username}"",
            ""html_url"": ""https://github.com/{username}"",
            ""type"": ""User"",
            ""site_admin"": false
        }}";
    }

    public void SetupNotFoundUser(string username)
    {
        _server.Given(Request.Create()
                .WithPath($"/users/{username}")
                .UsingGet())
            .RespondWith(Response.Create()
                .WithBody(GenerateNotFoundGitHubUserResponseBody())
                .WithHeader("content-type", "application/json; charset=utf-8")
                .WithStatusCode(HttpStatusCode.Forbidden));
    }
    private static string GenerateNotFoundGitHubUserResponseBody()
    {
        return $@"{{
            ""message"": ""Not Found"",
            ""documentation_url"": ""https://docs.github.com/rest/users/users#get-a-user""
        }}";
    }

    public void Dispose()
    {
        _server.Stop();
        _server.Dispose();
    }
}
```

**Comment by bnaya-corp** [comment]
# Docker

- [WIKI on Payoneer](https://dev.azure.com/Payoneer/Payoneer/_wiki/wikis/Payoneer.wiki/19779/AAS-UI)
